### ISSUE TITLE
`autocorrelate` breaks when using `autocorrelations` function argument 

### ISSUE THREAD

**Issue by fredhohman** [materialsinnovation/pymks#285]
When executing 

`X_auto = autocorrelate(X, p_basis, periodic_axes=[0, 1], autocorrelations=[(2, 2)])`

I received the following error:

```
Traceback (most recent call last):
  File "phase3.py", line 47, in <module>
    X_auto = autocorrelate(Xt, p_basis, periodic_axes=[0, 1], autocorrelations=[(2, 2)])
  File "/Users/fredhohman/anaconda/lib/python2.7/site-packages/pymks/stats.py", line 52, in autocorrelate
    return _compute_stats(X, basis, correlations, confidence_index,
UnboundLocalError: local variable 'correlations' referenced before assignment
```

**Comment by wd15** [comment]
This is not an issue in `pymks.fmks` which will replace `pymks`
