### ISSUE TITLE
Unable to build Sfepy in Python 3 for Conda

### ISSUE THREAD

**Issue by wd15** [materialsinnovation/pymks#323]
Unable to build Sfepy this with `conda build .` for Python 3.5 in the `builds/conda/sfepy` directory. However, can build when using `python setup.py install`,
but not with Conda. The error was

```Traceback (most recent call last):
  File "/home/wd15/anaconda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/wd15/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 246, in main
    execute(sys.argv[1:])
  File "/home/wd15/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 238, in execute
    already_built=None, config=config)
  File "/home/wd15/anaconda/lib/python2.7/site-packages/conda_build/api.py", line 83, in build
    need_source_download=need_source_download, config=config)
  File "/home/wd15/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 1081, in build_tree
    config=recipe_config)
  File "/home/wd15/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 784, in build
    entry_point_script_names = get_entry_point_script_names(get_entry_points(config, m))
  File "/home/wd15/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 352, in get_entry_points
    setup_py_data = jinja_context.load_setup_py_data(config)
  File "/home/wd15/anaconda/lib/python2.7/site-packages/conda_build/jinja_context.py", line 140, in load_setup_py_data
    exec(code, ns, ns)
  File "/home/wd15/anaconda/conda-bld/sfepy_1475788802642/work/setup.py", line 234, in <module>
    setup_package()
  File "/home/wd15/anaconda/conda-bld/sfepy_1475788802642/work/setup.py", line 200, in setup_package
    fdi = open(filename_in, 'r')
```

**Comment by wd15** [comment]
This works now.
